# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_auto_20170715_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='league',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='leagues.League'),
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.TextField(default='', max_length=20),
        ),
    ]
