# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_auto_20170715_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(related_name='matches', through='leagues.MatchParticipant', to='leagues.Player'),
        ),
    ]
