# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_auto_20170715_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='label',
            field=models.TextField(default='', max_length=40),
        ),
    ]
